# -*- coding: utf-8 -*-
"""imu_verify.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vOY5kJAf_yqcieoAlnRckYTaPtsJhPGa
"""

!pip install pandas
!pip install numpy
!pip install matplotlib
!pip install seaborn

file_path_imu = "/content/recording1.imu"

"""**1. Reading .imu (Binary → Structured Data)**


Header = 64 bytes

Each sample = 76 bytes

Timestamp = uint64 (nanoseconds)

Data = float32 values


✅ Already in SI units

✅ Already fused (quat available)

✅ Already gravity removed (lin_accel)
"""

import struct
import numpy as np

def read_imu(file_path):
    with open(file_path, "rb") as f:
        # --- Read header (64 bytes) ---
        header = f.read(64)

        magic = header[:8].decode()
        version = struct.unpack("<I", header[8:12])[0]
        sample_rate = struct.unpack("<I", header[12:16])[0]

        start_time_ns = struct.unpack("<Q", header[24:32])[0]

        print("Magic:", magic)
        print("Version:", version)
        print("Configured Sample Rate:", sample_rate)

        # --- Read samples ---
        samples = []

        while True:
            data = f.read(76)
            if len(data) < 76:
                break

            unpacked = struct.unpack("<Q 3f 3f 3f f 4f 3f", data)

            sample = {
                "timestamp_ns": unpacked[0],
                "accel": unpacked[1:4],
                "gyro": unpacked[4:7],
                "mag": unpacked[7:10],
                "temp": unpacked[10],
                "quat": unpacked[11:15],
                "lin_accel": unpacked[15:18]
            }

            samples.append(sample)

    return samples

samples = read_imu(file_path_imu)

samples



"""**2. Reading .vts (Frame ↔ Timestamp mapping)**


Header = 32 bytes

Entry = 12 bytes

frame_number → uint32

timestamp_ns → uint64
"""

file_path_vts = "/content/recording1.vts"

def read_vts(file_path):
    with open(file_path, "rb") as f:
        header = f.read(32)

        entries = []

        while True:
            data = f.read(12)
            if len(data) < 12:
                break

            frame_number, timestamp_ns = struct.unpack("<IQ", data)

            entries.append({
                "frame": frame_number,
                "timestamp_ns": timestamp_ns
            })

    return entries

vts_content = read_vts(file_path_vts)

vts_content

"""**Compute IMU Frequency**"""

def compute_frequency(imu_samples):
    timestamps = np.array([s["timestamp_ns"] for s in imu_samples])

    # Convert to seconds
    timestamps = timestamps * 1e-9

    # Differences
    dt = np.diff(timestamps)

    avg_dt = np.mean(dt)

    freq = 1.0 / avg_dt

    print("Average dt:", avg_dt)
    print("Computed Frequency:", freq)

    return freq

frequency_imu = compute_frequency(samples)

"""**Method 2: Sanity check using duration**"""

def frequency_sanity_check(imu_samples):
    t0 = imu_samples[0]["timestamp_ns"]
    t1 = imu_samples[-1]["timestamp_ns"]

    duration = (t1 - t0) * 1e-9
    N = len(imu_samples)

    freq = N / duration

    print("Sanity Frequency:", freq)
    return freq

test_frequency = frequency_sanity_check(samples)

